; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v2.1.4 on Fri Apr 17 2020 09:23:07 GMT+0100 (British Summer Time)
G91               ; relative positioning
G1 H1 Y-600 F1800 ; move quickly to Y axis endstop and stop there (first pass)
G1 H2 Y5 F6000    ; go back a few mm
G1 H1 Y-600 F360  ; move slowly to Y axis endstop once more (second pass)
G1 H2 Y1 F6000
G90               ; absolute positioning

