; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v2.1.4 on Fri Apr 17 2020 09:23:07 GMT+0100 (British Summer Time)
G91               ; relative positioning
G1 H1 Z200 F3000
G1 H2 Z-5 F3000
G1 H1 Z5 F180
G1 H2 Z-5 F3000
G90

