; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.4 on Fri Apr 17 2020 09:23:08 GMT+0100 (British Summer Time)
; Wait for set temperatures to be reached
M116 P0

